"""empty message

Revision ID: d5e5a1f6669b
Revises: 18866de02fab
Create Date: 2023-08-23 15:24:43.949350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e5a1f6669b'
down_revision = '18866de02fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caught__pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abilities', sa.String(), nullable=False),
    sa.Column('base_experience', sa.Integer(), nullable=False),
    sa.Column('sprites', sa.String(), nullable=False),
    sa.Column('hp', sa.String(), nullable=False),
    sa.Column('attack', sa.String(), nullable=False),
    sa.Column('defense', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caught__pokemon')
    # ### end Alembic commands ###
